export const TOPIC_ORDER = [
  { id: "js-grammar-types", title: "JS Grammar and Types" },
  {
    id: "js-control-flow-error-handling",
    title: "JS Control Flow and Error Handling",
  },
  { id: "js-loops-iteration", title: "JS Loops and Iteration" },
  { id: "js-functions", title: "JS Functions" },
  {
    id: "js-expressions-operators",
    title: "JS Expressions and Operators",
  },
  { id: "js-numbers-strings", title: "JS Numbers and Strings" },
  { id: "js-dates-times", title: "JS Representing Dates and Times" },
  { id: "js-regular-expressions", title: "JS Regular Expressions" },
  { id: "js-indexed-collections", title: "JS Indexed Collections" },
  { id: "js-keyed-collections", title: "JS Keyed Collections" },
  { id: "js-working-with-objects", title: "JS Working with Objects" },
  { id: "js-using-classes", title: "JS Using Classes" },
  { id: "js-using-promises", title: "JS Using Promises" },
  { id: "js-typed-arrays", title: "JS Typed Arrays" },
  {
    id: "js-iterators-generators",
    title: "JS Iterators and Generators",
  },
  { id: "js-resource-management", title: "JS Resource Management" },
  {
    id: "js-internationalization",
    title: "JS Internationalization",
  },
  { id: "js-modules", title: "JS Modules" },
  { id: "js-language-overview", title: "JS Language Overview" },
  { id: "js-data-structures", title: "JS Data Structures" },
  {
    id: "js-enumerability-ownership",
    title: "JS Enumerability and Ownership",
  },
  { id: "js-prototype-chain", title: "JS Prototype Chain" },
  { id: "js-equality-sameness", title: "JS Equality and Sameness" },
  { id: "js-closures", title: "JS Closures" },
  { id: "js-meta-programming", title: "JS Meta Programming" },
  { id: "js-memory-management", title: "JS Memory Management" },
  { id: "py-syntax", title: "Python Syntax" },
  { id: "py-output", title: "Python Output" },
  { id: "py-comments", title: "Python Comments" },
  { id: "py-variables", title: "Python Variables" },
  { id: "py-data-types", title: "Python Data Types" },
  { id: "py-numbers", title: "Python Numbers" },
  { id: "py-casting", title: "Python Casting" },
  { id: "py-strings", title: "Python Strings" },
  { id: "py-booleans", title: "Python Booleans" },
  { id: "py-operators", title: "Python Operators" },
  { id: "py-lists", title: "Python Lists" },
  { id: "py-tuples", title: "Python Tuples" },
  { id: "py-sets", title: "Python Sets" },
  { id: "py-dictionaries", title: "Python Dictionaries" },
  { id: "py-if-else", title: "Python If Else" },
  { id: "py-match", title: "Python Match" },
  { id: "py-while-loops", title: "Python While Loops" },
  { id: "py-for-loops", title: "Python For Loops" },
  { id: "py-functions", title: "Python Functions" },
  { id: "py-range", title: "Python Range" },
  { id: "py-arrays", title: "Python Arrays" },
  { id: "py-iterators", title: "Python Iterators" },
  { id: "py-modules", title: "Python Modules" },
  { id: "py-dates", title: "Python Dates" },
  { id: "py-math", title: "Python Math" },
  { id: "py-json", title: "Python JSON" },
  { id: "py-regex", title: "Python RegEx" },
  { id: "py-pip", title: "Python PIP" },
  { id: "py-try-except", title: "Python Try Except" },
  {
    id: "py-string-formatting",
    title: "Python String Formatting",
  },
  { id: "py-none", title: "Python None" },
  { id: "py-user-input", title: "Python User Input" },
  { id: "py-virtualenv", title: "Python VirtualEnv" },
  { id: "py-classes", title: "Python Classes" },
  { id: "py-oop", title: "Python OOP" },
  { id: "py-classes-objects", title: "Python Classes and Objects" },
  { id: "py-init-method", title: "Python __init__ Method" },
  { id: "py-self-parameter", title: "Python self Parameter" },
  { id: "py-class-properties", title: "Python Class Properties" },
  { id: "py-class-methods", title: "Python Class Methods" },
  { id: "py-inheritance", title: "Python Inheritance" },
  { id: "py-polymorphism", title: "Python Polymorphism" },
  { id: "py-encapsulation", title: "Python Encapsulation" },
  { id: "py-inner-classes", title: "Python Inner Classes" },
  { id: "py-file-handling", title: "Python File Handling" },
  { id: "py-read-files", title: "Python Read Files" },
  { id: "py-write-create-files", title: "Python Write Create Files" },
  { id: "py-delete-files", title: "Python Delete Files" },
  { id: "py-numpy", title: "NumPy Tutorial" },
  { id: "py-pandas", title: "Pandas Tutorial" },
  { id: "py-scipy", title: "SciPy Tutorial" },
  { id: "py-django", title: "Django Tutorial" },
  { id: "py-mysql", title: "Python MySQL Tutorial" },
  { id: "py-mongodb", title: "Python MongoDB Tutorial" },
  { id: "mpl-intro", title: "Matplotlib Intro" },
  { id: "mpl-get-started", title: "Matplotlib Get Started" },
  { id: "mpl-pyplot", title: "Matplotlib Pyplot" },
  { id: "mpl-plotting", title: "Matplotlib Plotting" },
  { id: "mpl-markers", title: "Matplotlib Markers" },
  { id: "mpl-line", title: "Matplotlib Line" },
  { id: "mpl-labels", title: "Matplotlib Labels" },
  { id: "mpl-grid", title: "Matplotlib Grid" },
  { id: "mpl-subplot", title: "Matplotlib Subplot" },
  { id: "mpl-scatter", title: "Matplotlib Scatter" },
  { id: "mpl-bars", title: "Matplotlib Bars" },
  { id: "mpl-histograms", title: "Matplotlib Histograms" },
  { id: "mpl-pie-charts", title: "Matplotlib Pie Charts" },
  { id: "ml-getting-started", title: "ML Getting Started" },
  { id: "ml-mean-median-mode", title: "ML Mean Median Mode" },
  { id: "ml-standard-deviation", title: "ML Standard Deviation" },
  { id: "ml-percentile", title: "ML Percentile" },
  { id: "ml-data-distribution", title: "ML Data Distribution" },
  {
    id: "ml-normal-data-distribution",
    title: "ML Normal Data Distribution",
  },
  { id: "ml-scatter-plot", title: "ML Scatter Plot" },
  { id: "ml-linear-regression", title: "ML Linear Regression" },
  {
    id: "ml-polynomial-regression",
    title: "ML Polynomial Regression",
  },
  { id: "ml-multiple-regression", title: "ML Multiple Regression" },
  { id: "ml-scale", title: "ML Scale" },
  { id: "ml-train-test", title: "ML Train Test" },
  { id: "ml-decision-tree", title: "ML Decision Tree" },
  { id: "ml-confusion-matrix", title: "ML Confusion Matrix" },
  {
    id: "ml-hierarchical-clustering",
    title: "ML Hierarchical Clustering",
  },
  { id: "ml-logistic-regression", title: "ML Logistic Regression" },
  { id: "ml-grid-search", title: "ML Grid Search" },
  { id: "ml-categorical-data", title: "ML Categorical Data" },
  { id: "ml-k-means", title: "ML K-means" },
  {
    id: "ml-bootstrap-aggregation",
    title: "ML Bootstrap Aggregation",
  },
  { id: "ml-cross-validation", title: "ML Cross Validation" },
  { id: "ml-auc-roc-curve", title: "ML AUC ROC Curve" },
  { id: "ml-k-nearest-neighbors", title: "ML K-nearest neighbors" },
  { id: "syntax", title: "Syntax and Keywords" },
  { id: "operators", title: "Operators and Expressions" },
  { id: "control-flow", title: "Control Flow" },
  { id: "imports-exports", title: "Import and Export" },
  { id: "packages-dependencies", title: "Packages and Dependencies" },
  { id: "comments", title: "Comments and Documentation" },
  { id: "linting", title: "Linting and Formatting" },
  { id: "variables", title: "Variables and Types" },
  { id: "data-types", title: "Data Types" },
  { id: "type-conversion", title: "Type Conversion" },
  { id: "strings", title: "Strings and Templates" },
  { id: "regex-patterns", title: "Regular Expressions" },
  { id: "numbers-math", title: "Numbers and Math" },
  { id: "booleans-logic", title: "Booleans and Logic" },
  { id: "loops", title: "Loops and Iteration" },
  { id: "iterators-generators", title: "Iterators and Generators" },
  { id: "objects-arrays-dicts", title: "Objects, Arrays, Dictionaries" },
  { id: "maps-sets", title: "Maps, Sets, and Collections" },
  { id: "functions-reduction", title: "Functions and Reduction" },
  { id: "scope-closures", title: "Scope and Closures" },
  { id: "async", title: "Async Programming" },
  { id: "events-reactivity", title: "Events and Reactivity" },
  { id: "error-handling", title: "Error Handling" },
  { id: "oop", title: "Object Oriented Patterns" },
  { id: "fp-patterns", title: "Functional Patterns" },
  { id: "architecture", title: "Architecture Patterns" },
  { id: "state-management", title: "State Management" },
  { id: "algorithms", title: "Algorithms and Complexity" },
  { id: "memory", title: "Memory and Data Lifetime" },
  { id: "concurrency", title: "Concurrency and Parallelism" },
  { id: "filesystem-io", title: "Filesystem and I/O" },
  { id: "networking-http", title: "Networking and HTTP" },
  { id: "api-methods", title: "API Methods and Contracts" },
  { id: "authn-authz", title: "Authentication and Authorization" },
  { id: "data-modeling", title: "Data Modeling" },
  { id: "databases", title: "Databases and Querying" },
  { id: "transactions", title: "Transactions and Consistency" },
  { id: "caching", title: "Caching and Performance Layers" },
  { id: "queues-jobs", title: "Queues and Background Jobs" },
  { id: "date-methods", title: "Date and Time Methods" },
  { id: "i18n-l10n", title: "Internationalization and Localization" },
  { id: "ui-rendering", title: "UI Rendering Patterns" },
  { id: "accessibility", title: "Accessibility" },
  { id: "logging", title: "Logging and Monitoring" },
  { id: "observability", title: "Observability and Tracing" },
  { id: "security-hardening", title: "Security Hardening" },
  { id: "profiling", title: "Profiling and Benchmarking" },
  { id: "testing", title: "Testing" },
  { id: "debugging", title: "Debugging" },
  { id: "cli-commands", title: "CLI Commands and Automation" },
  { id: "tooling-ci", title: "Tooling and CI" },
  { id: "build-release", title: "Build and Release" },
  { id: "project-structure", title: "Project Structure" },
  { id: "version-control", title: "Version Control Workflows" },
  { id: "code-review", title: "Code Review Practices" },
  { id: "initialization", title: "Initialization" },
  { id: "environment-config", title: "Environment and Configuration" },
  { id: "deployment", title: "Deployment" },
  { id: "common-errors", title: "Common Error Tips" },
  { id: "best-practices", title: "Performance and Security" },
] as const;

export const LANGUAGE_INFO = {
  python: {
    title: "Python",
    accent: "bg-emerald-400/20 text-emerald-800 border-emerald-600/30",
    description:
      "Readable backend and data language with batteries included for APIs, automation, and science.",
  },
  javascript: {
    title: "JavaScript",
    accent: "bg-amber-400/20 text-amber-800 border-amber-600/30",
    description:
      "The language of the web with event loops, async flows, and a rich runtime ecosystem.",
  },
  typescript: {
    title: "TypeScript",
    accent: "bg-sky-400/20 text-sky-800 border-sky-600/30",
    description:
      "Type-safe JavaScript for large applications, APIs, and maintainable frontend systems.",
  },
  sql: {
    title: "SQL",
    accent: "bg-rose-400/20 text-rose-800 border-rose-600/30",
    description:
      "Declarative querying language for modeling, retrieving, and optimizing relational data.",
  },
  bash: {
    title: "Bash",
    accent: "bg-lime-400/20 text-lime-800 border-lime-600/30",
    description:
      "Shell scripting language for automation, tooling, and reliable command-line workflows.",
  },
  react: {
    title: "React",
    accent: "bg-cyan-400/20 text-cyan-800 border-cyan-600/30",
    description:
      "Component-driven UI framework for predictable state, rendering, and app architecture.",
  },
} as const;

export type LanguageSlug = keyof typeof LANGUAGE_INFO;
export type TopicSlug = (typeof TOPIC_ORDER)[number]["id"];

export function isLanguageSlug(value: string): value is LanguageSlug {
  return value in LANGUAGE_INFO;
}

export function isTopicSlug(value: string): value is TopicSlug {
  return TOPIC_ORDER.some((topic) => topic.id === value);
}
